services:
  velocity-test:
    build:
      context: ./image
      args:
        VELOCITY_JAR_URL: ${VELOCITY_JAR_URL}
        VIAVERSION_JAR_URL: ${VIAVERSION_JAR_URL}
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:25577"
      - "${DASHBOARD_PORT}:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
      MOTD: ${MOTD}
      ONLINE_MODE: ${ONLINE_MODE}
      FORCE_KEY_AUTH: ${FORCE_KEY_AUTH}
      PREVENT_CLIENT_PROXY_CONNECTIONS: ${PREVENT_CLIENT_PROXY_CONNECTIONS}
      PING_PASSTHROUGH: ${PING_PASSTHROUGH}
      SAMPLE_PLAYERS: ${SAMPLE_PLAYERS}
      ENABLE_PLAYER_ADDRESS_LOGGING: ${ENABLE_PLAYER_ADDRESS_LOGGING}
      ANNOUNCE_FORGE: ${ANNOUNCE_FORGE}
      KICK_EXISTING_PLAYERS: ${KICK_EXISTING_PLAYERS}
      BUNGEE_PLUGIN_MESSAGE_CHANNEL: ${BUNGEE_PLUGIN_MESSAGE_CHANNEL}
      LOG_COMMAND_EXECUTIONS: ${LOG_COMMAND_EXECUTIONS}
      LOG_PLAYER_CONNECTIONS: ${LOG_PLAYER_CONNECTIONS}
      FAILOVER_ON_UNEXPECTED: ${FAILOVER_ON_UNEXPECTED}
      HAPROXY_PROTOCOL: ${HAPROXY_PROTOCOL}
      TCP_FAST_OPEN: ${TCP_FAST_OPEN}
      ACCEPTS_TRANSFERS: ${ACCEPTS_TRANSFERS}
      ENABLE_REUSE_PORT: ${ENABLE_REUSE_PORT}
      COMMAND_RATE_LIMIT: ${COMMAND_RATE_LIMIT}
      FORWARD_COMMANDS_IF_RATE_LIMITED: ${FORWARD_COMMANDS_IF_RATE_LIMITED}
      KICK_AFTER_RATE_LIMITED_COMMANDS: ${KICK_AFTER_RATE_LIMITED_COMMANDS}
      TAB_COMPLETE_RATE_LIMIT: ${TAB_COMPLETE_RATE_LIMIT}
      KICK_AFTER_RATE_LIMITED_TAB_COMPLETES: ${KICK_AFTER_RATE_LIMITED_TAB_COMPLETES}
      QUERY_ENABLED: ${QUERY_ENABLED}
      QUERY_PORT: ${QUERY_PORT}
      QUERY_SHOW_PLUGINS: ${QUERY_SHOW_PLUGINS}
      COMPRESSION_THRESHOLD: ${COMPRESSION_THRESHOLD}
      COMPRESSION_LEVEL: ${COMPRESSION_LEVEL}
      LOGIN_RATELIMIT: ${LOGIN_RATELIMIT}
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT}
      READ_TIMEOUT: ${READ_TIMEOUT}
      SERVER_IP_LOBBY0: ${SERVER_IP_LOBBY0}
      SERVER_IP_LOBBY1: ${SERVER_IP_LOBBY1}
      SERVER_IP_LOBBY2: ${SERVER_IP_LOBBY2}
      SERVER_IP_LOBBY3: ${SERVER_IP_LOBBY3}
      SERVER_IP_LOBBY4: ${SERVER_IP_LOBBY4}
      SERVER_IP_HG0: ${SERVER_IP_HG0}
      SERVER_IP_HG1: ${SERVER_IP_HG1}
      SERVER_IP_HG2: ${SERVER_IP_HG2}
      SERVER_IP_HG3: ${SERVER_IP_HG3}
      SERVER_IP_HG4: ${SERVER_IP_HG4}
      VELOCITY_SECRET: ${VELOCITY_SECRET}
